nohup sh mytest_d3_epoch2_run1.sh & 
nohup sh mytest_d3_epoch2_run2.sh & 
nohup sh mytest_d3_epoch2_run3.sh &
nohup sh mytest_d5_epoch2_run1.sh & 
nohup sh mytest_d5_epoch2_run2.sh & 
nohup sh mytest_d5_epoch2_run3.sh &
nohup sh mytest_d7_epoch2_run1.sh & 
nohup sh mytest_d7_epoch2_run2.sh & 
nohup sh mytest_d7_epoch2_run3.sh &
nohup sh mytest_d9_epoch2_run1.sh & 
nohup sh mytest_d9_epoch2_run2.sh & 
nohup sh mytest_d9_epoch2_run3.sh &
nohup sh mytest_d11_epoch2_run1.sh & 
nohup sh mytest_d11_epoch2_run2.sh & 
nohup sh mytest_d11_epoch2_run3.sh &
nohup sh mytest_d13_epoch2_run1.sh & 
nohup sh mytest_d13_epoch2_run2.sh & 
nohup sh mytest_d13_epoch2_run3.sh &
